#!/bin/bash
status_code=`curl -s -o /dev/null -w "%{http_code}" localhost:8080/sample/`
if [[ $status_code -eq 200 ]]; then
    echo "Tomcat Application running and working properly"
else
    echo "Tomcat Application is not running! Check the logs!!!"
fi
